services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=employees
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python app.py 0.0.0.0:8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - EMPLOYEES_DATABASE_URL=postgresql://postgres:postgres@db:5432/employees
    depends_on:
      - db

volumes:
  postgres_data:
